# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'reddit-clone' do
  # Comment the next line if you don't want to use dynamic frameworks
  platform :ios, '15.0'
  use_frameworks!

  # Pods for reddit-clone
  pod 'SideMenu', '~> 6.0'
  pod 'Tabman', '~> 2.11'
  pod 'IQKeyboardManagerSwift'
end
