# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'Waddit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for Waddit
  pod 'SwiftLint'
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'

end
